version: '3'
services:
  relay:
    build:
      context: ./
      dockerfile: Dockerfile.relay
    ports:
      - 8000:8000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
